### ISSUE TITLE
Report by criticity card is empty

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#151]
The report by criticity card is empty

![image](https://user-images.githubusercontent.com/17493961/169650422-cbe0547e-57aa-4373-bb20-d51f1ae8ae5c.png)

**Comment by Serizao** [comment]
Have you got sync the data before ? card seem work on my environnement can you check if you have some error in the devTool console ?

**Comment by JoshuaMart** [comment]
After a refresh seem's to work but the "Exceptional" status is missing for Intigriti
