### ISSUE TITLE
Missing reports status for Intigriti

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#152]
It seems that there are missing statuses for the status of the intigriti reports.
A report can have one of the following status :
```
NA
Spam
Out Of Scope
Informative
Accepted Risk
Duplicate
Resolved
Accepted
Triaged
Draft
```

**Comment by Serizao** [comment]
it work on my environnement
![image](https://user-images.githubusercontent.com/11671895/169691453-2f6793be-390b-4e64-8741-1b2fe9f2308e.png)
Have you got some report with the cited status ?

**Comment by JoshuaMart** [comment]
I think you're looking to YesWeHack, not Intigriti, `Not Applicable` doesn't exist for Intigriti
[EDIT] : After a double check it's looks good, I will reopen the issue if necessary
