### ISSUE TITLE
Wrong filtering for leaks

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#157]
Using the leaks filtering feature, the value of the field is added as a parameter name instead of the value of the domain field.
Example :
```
https://hunt3r.domain.tld/api/leaks?domain.tld=&page=1&limit=10
```

**Comment by Serizao** [comment]
This issue is already fix on https://github.com/EasyRecon/Hunt3r/commit/b0762b7c2820b12d84e15964b2402c0a70538f96
