### ISSUE TITLE
Display the cost on a scan

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#170]
In addition to displaying the cost on a server it would be interesting to display the cost directly on the page of scans.

Because when a server is deleted, it is no longer present in the UI and therefore we lose the information while at the base this information is well attached to a scan.

![image](https://user-images.githubusercontent.com/17493961/169688101-1e3b1c15-508e-4d71-80ea-272d8f144215.png)

**Comment by Serizao** [comment]
done on #186
