### ISSUE TITLE
on pagination system, number of item on one page -1 value must return all item

### ISSUE THREAD

**Issue by Serizao** [EasyRecon/Hunt3r#178]

**Comment by JoshuaMart** [comment]
I don't understand the problem, can you elaborate? :)

**Comment by Serizao** [comment]
^^ of course : 
for exemple the query `https://domain.tld/api/domains?limit=10&page=1&domain=&url=&status_code=&technology=` must return page one with 10 item by page. And the query `https://domain.tld/api/domains?limit=-1&page=1&domain=&url=&status_code=&technology=` must return all item stored in the database

limit -1 equal to no limit
