### ISSUE TITLE
Updating the date of a domain when re-running a scan

### ISSUE THREAD

**Issue by Serizao** [EasyRecon/Hunt3r#185]
I have lauch a scan on domain.tld a first time at 2022-05-16 and i have lauch a second time the scan on the same domain at 2022-05-22 and the return field `updated_at` stay on the first scan date (2022-05-16)

**Comment by JoshuaMart** [comment]
You mean the `last_scan` field on a scope ?

**Comment by Serizao** [comment]
nope on the call `/api/domains?limit=10&page=1&domain=&url=&status_code=&technology=` the field `updated_at`
![image](https://user-images.githubusercontent.com/11671895/169698266-ce70de9c-ebef-4474-af92-12050bc9584e.png)

**Comment by JoshuaMart** [comment]
Ok I understand
This field was not intended to be updated at the base, simply.
But yes, it would be useful to see the date of last scan of a domain
