### ISSUE TITLE
Bug on vulnerability pagination when all item (limit=-1) are displayed

### ISSUE THREAD

**Issue by Serizao** [EasyRecon/Hunt3r#191]
The request `https://domain.tld/api/vulnerabilities?limit=-1&page=1&severity=` throw an error

![image](https://user-images.githubusercontent.com/11671895/169707822-219dadc6-c41f-4e97-83da-354eb6a0a6a1.png)

**Comment by JoshuaMart** [comment]
https://github.com/EasyRecon/Hunt3r/pull/193
