### ISSUE TITLE
Hackerone connection error

### ISSUE THREAD

**Issue by Serizao** [EasyRecon/Hunt3r#280]
Backend seem not accept hackerone connection i try with email & api token generated from my hackerone profil. 

Backend response:
![image](https://user-images.githubusercontent.com/11671895/185852345-57f7db86-83fb-4d70-9737-9019d48216af.png)

**Comment by JoshuaMart** [comment]
Fixed on the backend, the email must be replaced by the username (hunter_username on API side) on the UI side
