### ISSUE TITLE
Add AWS as Cloud Provider

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#5]
Currently only Scaleway is managed as a Cloud Provider.
It would be interesting to add others, notably AWS, as a first step

**Comment by JoshuaMart** [comment]
Backend part added with #232

Frontend part could be added now @Serizao

**Comment by Serizao** [comment]
done in #241

**Comment by JoshuaMart** [comment]
- There is only the addition of the provider but not the selection in the engine
