### ISSUE TITLE
Normalize YWH scopes

### ISSUE THREAD

**Issue by JoshuaMart** [EasyRecon/Hunt3r#7]
Normalize YesWeHack scopes to avoid things like the following in output
```
*.domain.(com|fr)
```

**Comment by rmarot** [comment]
I have something for this, I think this can handle the following (seen on various programs across the platforms) : 
```
*.domain.(com|fr)
*.domain.<com|fr>
*.domain.[com|fr]
```

**Comment by JoshuaMart** [comment]
I added a trick to normalize some of the scopes.
I tested with the following cases:
```
*.domain.(com|fr)
*.domain.(com|fr) (+++)
```

So according to your example it's not totally functional, anyway the part of code for normalization is present, we just need to modify it :)
